/*
Jay Howard
Excercise 3.11.1 String Representation
Write a gerneric function to_string that takes an argument of an arbitrary type (as const&) and generates a string by piping it to a std::stringstream and returning the result string.

Excercise 3.11.2 String Representation of Tuples
Write a variadic template function that represents an arbitrary number of arguments as a tuple in a string. That is, the function call to_tuple_(x,y,z) returns a string of the form (x, y, z) by printing each element to a string stream. Hint: Use a help function to_tuple_string_aux that is overloaded for different arities.
*/

#include<string>
#include<sstream>
#include<iostream>
using namespace std;


//Returns string generated by passing the argument to a stringstream
template <typename T>
inline string to_string(const T& from) {
	stringstream to;
	to << from;
	return to.str();
}

inline string to_tuple() { return "()"; }

template <typename T>
inline string to_tuple(T t) { return to_string(t); }

template <typename T, typename ...P>
inline string to_tuple(T t,P ... p) { return to_tuple_string_aux(t, p...) + to_tuple(p...); }

//Auxiliary
template<typename T>
inline string to_tuple_string_aux(T t) { return "(" + to_string(t) + ")"; }
template<typename T, typename ...P>
inline string to_tuple_string_aux(T t, P ...p) { return to_string(t) + ", "; }

int main() {
	auto testString = "This is a string";
	auto testChar = 'c';
	auto testInt = "42";

	cout << to_string(testString) << endl << to_string(testChar) << endl << to_string(testInt) << endl << to_string("This is an rvalue") << endl;

	cout << to_tuple("this is a single argumetn to tuple") << endl;
	cout << to_tuple("this is a tuple", "from a variadic template." ," take 3", 12) << endl;
	system("PAUSE");
	return 0;
}